pysal/pysal.github.io

_config.yml, _includes/funding.md, _includes/news.md, _includes/upcoming_events.md, _site/funding.html, _site/news.html, _site/upcoming_events.html
* add NARSC 2017 workshop to upcoming events
* fix broken funding links
* fix deprecated 'pygments' configuration
=> add NARSC 2017 workshop

_sources/news.rst.txt, news.html
Please enter the commit message for your changes. Lines starting
=> delete duplicate news

.buildinfo, _sources/index.rst.txt, _sources/news.rst.txt, _static/basic.css, _static/doctools.js, _static/language_data.js, _static/searchtools.js, _static/websupport.js, about.html, contact.html, docs.html, gallery.html, genindex.html, getting_started.html, index.html, install.html, news.html, search.html, team.html
This PR is to fix spreg links on the landing page https://github.com/pysal/pysal.github.io/issues/85 without adding sidebars https://github.com/pysal/pysal.github.io/pull/88
=> fix spreg links on the landing page 

_data/news.yml
* news for `spaghetti v1.3` release
=> update spaghetti news

getting_started.md
This PR is to add link to the release instructions
=> add link to release instructions

_data/news.yml
add mapclassify 2.1, splot 1.1 and splot 1.0 releases to `_data.yml`
=> add mapclassify 2.1, splot 1.1 and splot 1.0 releases to `_data.yml`

_data/news.yml
=> spaghetti release news

getting_started.md
address https://github.com/pysal/pysal.github.io/issues/114
=> add instructions to publish docs with github page

_data/documentation.yml
updating spaghetti website following switch to GitHub hosted docs
=> updating spaghetti website

_data/core.yml
* Gaboardi ~~FSU~~ --> Penn State
* Folch ~~FSU~~ --> Northern Arizona
=> affiliation update

_data/documentation.yml
Addresses https://github.com/pysal/libpysal/issues/205
=> Bug: stale libpysal link

install.md
this is a fix for https://github.com/pysal/pysal.github.io/pull/124/files#diff-edb274d8c594429b8ccc684d79d771f6
=> conda forge install

_data/news.yml
libpysal v4.2.0 release announcement
=> libpysal v4.2.0 news

_data/news.yml
Adding news update for spaghetti v1.4.0 release.
=> spaghetti v1.4.0 news

_data/news.yml
bug fix for spaghetti news
https://github.com/pysal/pysal.github.io/runs/373103669
=> bug fix for spaghetti news

_data/news.yml
=> fixing spaghetti v1.4.1 news

_data/documentation.yml
Addressing part of https://github.com/pysal/esda/issues/107.
=> DOC: update esda landing page

_data/news.yml
update spaghetti news for release
=> spaghetti news

getting_started.md
The PR contains updates (giddy's doc website is used as an example and it has recently been updated) and minor fixes to the [getting_started page](http://pysal.org/getting_started).
=> updates and minor fixes to the getting_started page

_data/news.yml
update spaghetti news for release
=> spaghetti news for v1.5.2

_data/news.yml
update DAB punctuation (!. --> !)
=> update DAB punctuation

content/model/spreg.md
=> update spreg docs link

content/team/gaboardi.md
=> update gaboardi affiliation

content/model/access.md
updating access link on the pysal website
=> updated access url

content/news/spopt_JOSS_paper.md
=> spopt JOSS news

content/news/spaghetti_1.6.8.md, content/news/spreg_1.3.0.md
add spaghetti & spreg releases to news
=> add spaghetti & spreg releases

content/news/spopt_0.5.0.md
blurb for spopt==0.5.0 release
=> blurb for spopt==0.5.0 release

content/explore/inequality.md
This PR updates the `inequality`  docs site address.
=> update inequality site

content/news/spopt_0.6.0.md
=> `spopt` v0.6.0 release news

content/community/_index.md
This PR updates the chat links from Gitter to Discord
* xref https://github.com/pysal/pysal/issues/1296
=> update chat links: gitter >> discord

content/news/libpysal_4.11.md
=> libpysal 4.11

content/news/libpysal_4.11.md
fixing #233 - libpysal 4.11 news
=> fixing #233 - libpysal 4.11 news

content/explore/pointpats.md
=> Update pointpats link within Explore
